### ISSUE TITLE
Command names cannot contain spaces

### ISSUE THREAD

**Issue by Bilge** [getopt-php/getopt-php#101]
I'd like to query why command names cannot contain spaces. Currently I receive an error similar to the following:

>InvalidArgumentException: Command name has to be an alphanumeric string not starting with dash, found 'import apps'

I want a command called `import apps` and another called `import reviews`. The thought occurs I could just create an *import* command with an operand that accepts either *apps* or *reviews*. The reason I cannot do this, however, is because each of those commands accept a different set of options. That is, since the commands do not share the same options they cannot be combined.

Is there any technical reason at all why a command could not contain a space character? If so, could such a restriction be lifted without too much effort?

**Comment by tflori** [comment]
the reason is that a space divides arguments. we would get `import` and `apps` - we don't find a command `import` and use it as operand.. the usual way (like symfony console is doing) is to use colons e. g. `import:apps`.

we could allow them but then you will need to add quotes arround this argument e. g. `php cli.php "import apps"`. im my opinion the colon is easier to type.

it's more like a command with sub commands. maybe we can think about a recursive command detection. :thinking:

**Comment by Bilge** [comment]
>the reason is that a space divides arguments.

I realise, but I thought since you have imposed the artificial constraint that commands must appear in the first position (before any other components), they'd be pre-stripped before doing any further processing on them. Therefore it shouldn't be possible to confuse the command portion with the operand portion?

**Comment by AnrDaemon** [comment]
In the most common case, you get command line already split into words. (`$_SERVER[argv]`)
Unless you explicitly quote your "spaced command", it will be split already and rebuilding it would be quite problematic (I mean, not without a lot of assumptions).
Technical intricacies aside, "command" is a [verb](https://en.wikipedia.org/wiki/Verb), which defines action. I haven't seen many verbs consisting of two words.

**Comment by tflori** [comment]
Basically that is correct. We could take the first operand search a command with this name, take the second, search a command with this name and so on till we either find one or store them all as operands.

But this happens in a loop where each word could be an option as well. So we would need another restriction that there can not be an option in between the command name operands. Otherwise a command line `php cli.php import --verbosity high reviews` would be misleading.

**Comment by tflori** [comment]
@Bilge please try the feature. One note: We search of command names until we find an option after an operand. So an option before the first operand is fine but not after the first operand: [see the test](https://github.com/getopt-php/getopt-php/pull/150/files#diff-6b4944ca4097b7fd9dd7052a269bc175R227)
