### ISSUE TITLE
Command options not shown in help output

### ISSUE THREAD

**Issue by Bilge** [getopt-php/getopt-php#102]
Although a richly detailed output is displayed for global options, command options are completely omitted from the help text, making such options undiscoverable by the user using the help system! I propose the same level of detail be present in the help output for each command with options.

**Comment by tflori** [comment]
when `GetOpt::process()` detects a command it adds the options and operands from this command to the `GetOpt` object. then `GetOpt::getHelpText()` also shows these options.

there is an error in the [example](http://getopt-php.github.io/getopt-php/example.html). in general you can see how to show help for a specific command.  we use `$getOpt->getCommand()` and when there is no command **or** the option `help` is given we show the help text. 

the problem is the exception thrown when a required operand is missing. to avoid this you could add something like this (what is really ugly):

```php
try {
    try {
        $getopt->process();
    } catch (Missing $exception) {
        if (!$getopt->getOption('help')) {
            throw $exception;
        }
    }
} catch (ArgumentException $exception) {
    file_put_contents('php://stderr', $exception->getMessage() . PHP_EOL);
    echo $getopt->getHelpText();
    exit;
}
```

**Comment by Bilge** [comment]
I'm not sure you understood my issue but I'm not sure it matters since I think I misunderstood how the help system is supposed to work WRT command options. Closing this.
