### ISSUE TITLE
Parsing fails on option-arguments beginning with a hyphen

### ISSUE THREAD

**Issue by okdana** [getopt-php/getopt-php#136]
GetOpt doesn't properly support option-arguments that begin with a hyphen. Specifically, it only handles them as expected when they're part of the same word/argument as the option itself:

```console
% composer require -q ulrichsg/getopt-php

% cat test.php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$getopt = new \GetOpt\GetOpt([
  (new \GetOpt\Option('f', 'foo', \GetOpt\GetOpt::REQUIRED_ARGUMENT)),
]);

try {
  $getopt->parse();
  echo $getopt->getOption('foo'), "\n";
} catch ( \Exception $e ) {
  echo $e->getMessage(), "\n";
}

% php test.php -f-1
-1
% php test.php -f -1
Option 'foo' must have a value

% php test.php --foo=-1
-1
% php test.php --foo -1
Option 'foo' must have a value
```

Not sure if this is intended to catch mistakes or if it's just an oversight, but it's contrary to the way POSIX/GNU-style argument parsers normally work, and it breaks many common use cases like negative numbers ~~and `-` as a short-hand for `stdin`/`stdout`~~. (Edit: Actually it does handle `-` correctly.)

If it *is* deliberate, could there be an option to disable it?

**Comment by tflori** [comment]
the thing is how this lib recognizes if the next argument is a value. it does so by checking if the next argument is not empty, is not a single dash and does not begin with dash. 

one solution would be: we could find out that the option can have an argument and use the next argument as the options argument regardless of the content. but then we would get unexpected behavior for options with optional argument. and if we check if it could be a value only when it is an optional argument we would have a difference between `-f -1` for optional argument and required argument.

the second option might be hard to explain but I would prefer this solution.

**Comment by okdana** [comment]
I know that some option parsers do behave as you described in your 'one solution'; for example, Perl's `Getopt::Long` and zsh's `zparseopts` built-in work that way. I think the default behaviour of Clap (the Rust argument parser) is like that as well.

Meanwhile, GNU's `getopt(3)` implementation requires that optional arguments be in the same word as the option (so `arg` is treated as an option-argument given `-farg` or `--foo=arg`, but not `-f arg` or `--foo arg`). I suspect that this is the most common behaviour, just due to how prolific GNU `getopt(3)` is, and it makes the most sense to me personally — any other way of handling it feels too 'magic' and makes too many assumptions about what the user might have meant.

That's my take. Thanks for looking at it, in any case!

**Comment by tflori** [comment]
Let's assume the check if it is an argument or the next option is valid. Then we have these ways to work / deal with it:

| name | description | optional argument | required argument |
|------|-------------|-------------------|-------------------|
| gnu  | GNUs way to deal with optional arguments for options. An optional argument needs to stay next to his option. | `-fbar` or `--foo=bar` | `--foo=bar` or `--foo -1` |
| legacy | Our current way of finding an argument. Either the argument stays next to his option or we check if the next parameter is not an option | `-f bar` or `--foo bar` or `-f-1` or `--foo=-1` | `-fbar` or `--foo bar` but **not** `--foo -1` |
| compat | Check if the next parameter is not an option if the argument is optional. It's a compromise between both. | `-f bar` or `--foo bar` or `-f-1` or `--foo=-1` | `-fbar` or `--foo bar` **and** `--foo -1` |

Anyway: because gnu solution would break working solutions we could only change with a new major version. What do you think? A new major version and hard coded GNU solution, an option in the current version with all 3 solutions or hard coded compat version?

**Comment by okdana** [comment]
Well, if it were my choice, i think i'd go the GNU route. But i may not be the best person to ask — i very rarely use optional-argument options anyway, so i won't personally suffer from the broken compatibility (nor from the maintenance load). Is there one that you favour?

**Comment by tflori** [comment]
I would also prefer the GNU version (for bash devs heart) but I would also prefer not to create a new major version for this. In this case the compatible version makes the most sense.

**Comment by okdana** [comment]
Fair. As long as it fixes the required-argument case i'll be happy enough.

**Comment by tflori** [comment]
Interesting there is also a test that explicitly tests this behavior:
```php
    public function testParseNoValueStartingWithHyphenRequired()
    {
        $this->setExpectedException('GetOpt\ArgumentException\Missing');
        $this->getopt->addOptions([
            new Option('a', null, GetOpt::REQUIRED_ARGUMENT),
            new Option('b', null)
        ]);
        $this->getopt->process('-a -b');
    }
```
