### ISSUE TITLE
Can help be a command?

### ISSUE THREAD

**Issue by tkaufmann** [getopt-php/getopt-php#157]
I'd prefer

`mycommand help`

over

`mycommand -h`

but GetHelpText() will return only the help text for the current command. Would be thankful for a quick hint!

**Comment by tflori** [comment]
I'm afraid at the moment there's no easy way to get this.

You could read `$_SERVER['argv']`manually and react differently when the first argument is `help`. But I would but recommend this because testing would be difficult.

You can get and extend the help class. It could be that there is a way to set or reset the command in the helper class.

**Comment by tkaufmann** [comment]
Thanks a lot for getting back!
