### ISSUE TITLE
Being able to pass options after operands

### ISSUE THREAD

**Issue by sagikazarmark** [getopt-php/getopt-php#39]
I am not sure which is the POSIX standard:

`command operand --help`: --help parsed as option

It would be good if the above example could work.

It is not that hard to implement it, however the `CommandLineParser` must loop through all the provided options. I can send a PR for it.

But I would like to know whether not supporting this is a decision made or just implemented this way.

**Comment by allmarkedup** [comment]
+ 1

I need this exact behaviour too. Seems like it is quite a common pattern and I can't see any downsides to supporting it?

**Comment by func0der** [comment]
Yep, I would find this very useful, too.
If you would not want to support it in your code, maybe you could make the CommandLineParser injectable so that we would be able to overwrite it ourselves.

**Comment by okdana** [comment]
I'm on mobile, so forgive me for that, but i can tell you that `--` has a special meaning in argument processing — it tells the parser to treat everything that follows as an operand, even if it begins with `-`. So `mycmd -- --not-an-option` lets `mycmd` know not to process `--not-an-option`. It's thrown away because it's only a 'meta' argument, it doesn't do anything but signify how the parser should treat the arguments following it. It should only be thrown away once though — `mycmd -- -a -- -b` should treat the second `--` as an operand.

`-` on the other hand is NOT special to the parser and has no 'meta' purpose. Without looking at the code, i'd guess the parser checks for it specially to make sure it doesn't flag it as an invalid short option.

**Comment by tavinus** [comment]
Thanks dude.   
So, from what I understand the proper solution seems to involve processing -- as a unique operand (where array slice even makes sense), but only once. While normal operands should be processed separatelly and without array_slice and treating all ese as an operand.  
I mean, any operand was being treated as a -- (breaking processing).

**Comment by tavinus** [comment]
**I need to ask though:  @ulrichsg, is this abandonned?**  
It has been more than 2 years since the last commit here.  
  
@tflori 's [fork](https://github.com/tflori/getopt-php) has many [patches](https://github.com/ulrichsg/getopt-php/compare/master...tflori:master) and maybe is a better one to use (and modify) at this point?  
  
We can't post issues there though. I can't really send messages to @tflori as well. So maybe we need somewhere else to continue this if @ulrichsg gave up on it.

**Comment by okdana** [comment]
The special behaviour of the `--` argument actually is in the POSIX spec — [Base Definitions, Utility Conventions, 12.2.10](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html). You're right that POSIX expects options to precede operands. AFAICT this project conforms to POSIX except that it adds support for GNU-style long options (`--foo`). It should probably conform completely to the expectations of one or the other rather than mixing them.

In any case, as you say, this project hasn't seen much activity in quite a while. At this point you're probably better served by [`Symfony\Console`](http://symfony.com/doc/current/console.html), which has become pretty much the de facto standard for writing PHP-based command-line tools.

If you want something lighter-weight, there's also [`Zend\Console\Getopt`](https://docs.zendframework.com/zend-console/getopt/intro/).

Unfortunately i feel like *none* of the available argument parsers for PHP is quite feature-complete. Most of them can't distinguish between multiple option invocations (`-v` vs `-vvv`), most don't elegantly support aliases (accepting `--nocolour` for `--no-colour`), and in general they don't expose state to options being parsed (so there's no way to tell the difference between `-qqvv` and `-qvqv`). I may have unusually high expectations of an argument parser, though, idk

**Comment by tflori** [comment]
we moved all together to getopt-php org.

I think that the GNU-style should be made possible. And therefore operands should not stop parsing. But the `--` should stop parsing anyway.

The best will be to be fully compatible to this definition:
https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html
