### ISSUE TITLE
Thoughts on the new Help customization framework

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#91]
In 3.0, the library allows 2 methods to customize the output of getHelpText: 
- via a class implementing GetOpt\HelpInterface, or 
- by writing custom template scripts, similar to those provided in resources/

I hope you won't mind my saying so, but I'm not very keen on the proposed approach, particularly the second one, and I think this should be improved. Here's a few issues I see:

1. having to create up to 3 custom templates (even as copies of the provided ones) and maintain them is cumbersome
2. there is some code and logic in the original templates which would be nice to be able to reuse as-is in custom ones
3. Some of this logic is duplicated (e.g. the console width detection is both in _options.php_ and _commands.php_
4. let's say I want to keep the standard template, but localize the output; I can't do that easily because some strings are hardcoded

The custom Help class is better, but still does not allow easy reuse of code in the default templates.

A couple of suggestions for improvement:
- instead of relying on standalone PHP scripts for templates and using output buffering to capture their output, let the _setXxxTemplate()_ methods accept a _callable_ instead, and put the contents of the script into methods of the Help class which will return a string instead of echoing.
- extract duplicated code into helper methods, to be used as building bricks for the callable
- provide a way to localize the output

Let me know your thoughts.

**Comment by tflori** [comment]
yeah, you know.. growing code :smile:

First it was just a small echo usage then this and that.. and column width and and and...

At a point I thought about implementing a text table library but they have too much code for such simple task with two columns.

I wanted to revise the help anyway because the operands don't have descriptions currently. Maybe to put everything into this help class and the devs can extend this Help class to customize.

Translation could be done by just providing an array for "Usage", "Options", "Operands" and "Commands". You know the reason not to use "symfony/console" is the size and no other dependencies.

But in general: yes, you are right. The implementation of help text generation is not my best work :smile:

**Comment by dregad** [comment]
> yeah, you know.. growing code :smile:

I know :wink:

> Translation could be done by just providing an array 

Yes, I guess that would work as a simple implementation. Or maybe use [Gettext](http://php.net/manual/en/book.gettext.php) although maybe that's overkill

**Comment by tflori** [comment]
@dregad do you think this is ok: https://github.com/getopt-php/getopt-php/commit/d7fd713c817304767b52e53c1d6086d907e8bd36 ?

I don't want to make too much effort but this is at least reusable (extend Help instead of create a own class).

In this version we need to keep the `set*Template` methods and it should work as before - otherwise we have a regressions of the public api. So I need to test using templates and mark the setters as deprecated.

**Comment by dregad** [comment]
> do you think this is ok: d7fd713 ?

@tflori sorry for the delayed response, I just saw your note today.

I had a look at the code, and ran a quick test to localize some of the strings - was initially a bit confused because what you implemented in the above-referenced commit was later changed, but I think it works quite effectively now - definitely a much better implementation than the original attempt with the template scripts !

It may be a nice feature for people like me who just need to translate the default texts, to provide an easy way to use another language (e.g. something like `$opt->setHelpLang('fr')`) and provide language the appropriate language strings as part of the package. What do you think ?

**Comment by tflori** [comment]
@dregad I updated the documentation in #106 and added a function to change the langue from GetOpt php. Can you provide a `fr.php` (either as PR or by pasting here or in my PR)? I know only English and German :smile: 

Please check the help description if it is enough to understand it. Than I will release 3.1 this weekend. Thanks!

**Comment by dregad** [comment]
Done
